name: Build EXE
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: 安装依赖
        run: pip install pyinstaller flask flask-sqlalchemy flask-login captcha geoip2
      - name: PyInstaller打包
        run: pyinstaller -F -c --noupx --disable-windowed-traceback syup_clean.py
      - name: 上传生成的exe
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.exe
